**

!deploy/
!deploy/jetson-readonly/
!deploy/jetson-readonly/config/
!deploy/jetson-readonly/config/**
!deploy/jetson-readonly/entrypoint.sh
!deploy/jetson-readonly/healthcheck.sh
!deploy/jetson-readonly/camera-quality-healthcheck.py
!deploy/jetson-readonly/validate-network.sh
!deploy/jetson-readonly/verify-runtime.sh

!scripts/
!scripts/check_runtime_ownership.sh
!scripts/runtime_lease.sh

!packages/
!packages/go2_chassis/
!packages/go2_chassis/include/
!packages/go2_chassis/include/go2_chassis/
!packages/go2_chassis/include/go2_chassis/**
!packages/go2_chassis/ros2_ws/
!packages/go2_chassis/ros2_ws/src/
!packages/go2_chassis/ros2_ws/src/go2_chassis_adapter/
!packages/go2_chassis/ros2_ws/src/go2_chassis_adapter/**

!packages/go2_sensors/
!packages/go2_sensors/CMakeLists.txt
!packages/go2_sensors/package.xml
!packages/go2_sensors/include/
!packages/go2_sensors/include/**
!packages/go2_sensors/src/
!packages/go2_sensors/src/**
!packages/go2_sensors/config/
!packages/go2_sensors/config/**
!packages/go2_sensors/launch/
!packages/go2_sensors/launch/**
!packages/go2_sensors/camera_daemon/
!packages/go2_sensors/camera_daemon/**

!packages/go2_description/
!packages/go2_description/CMakeLists.txt
!packages/go2_description/package.xml
!packages/go2_description/LICENSE.unitree
!packages/go2_description/dae/
!packages/go2_description/dae/**
!packages/go2_description/urdf/
!packages/go2_description/urdf/**

!third_party/
!third_party/unitree_ros2/
!third_party/unitree_ros2/cyclonedds_ws/
!third_party/unitree_ros2/cyclonedds_ws/src/
!third_party/unitree_ros2/cyclonedds_ws/src/unitree/
!third_party/unitree_ros2/cyclonedds_ws/src/unitree/unitree_api/
!third_party/unitree_ros2/cyclonedds_ws/src/unitree/unitree_api/**
!third_party/unitree_ros2/cyclonedds_ws/src/unitree/unitree_go/
!third_party/unitree_ros2/cyclonedds_ws/src/unitree/unitree_go/**

!third_party/unitree_sdk2/
!third_party/unitree_sdk2/CMakeLists.txt
!third_party/unitree_sdk2/LICENSE
!third_party/unitree_sdk2/cmake/
!third_party/unitree_sdk2/cmake/**
!third_party/unitree_sdk2/include/
!third_party/unitree_sdk2/include/**
!third_party/unitree_sdk2/lib/
!third_party/unitree_sdk2/lib/aarch64/
!third_party/unitree_sdk2/lib/aarch64/**
!third_party/unitree_sdk2/licenses/
!third_party/unitree_sdk2/licenses/**
!third_party/unitree_sdk2/thirdparty/
!third_party/unitree_sdk2/thirdparty/CMakeLists.txt
!third_party/unitree_sdk2/thirdparty/include/
!third_party/unitree_sdk2/thirdparty/include/**
!third_party/unitree_sdk2/thirdparty/lib/
!third_party/unitree_sdk2/thirdparty/lib/aarch64/
!third_party/unitree_sdk2/thirdparty/lib/aarch64/**
