#!/usr/bin/env bash
set -euo pipefail

readonly DEPLOY_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly WORKSPACE_ROOT="$(CDPATH= cd -- "$DEPLOY_DIR/../.." && pwd)"
readonly CLIENT_ROOT="$WORKSPACE_ROOT/upstream/robonix-client"
readonly CLIENT_BIN="$CLIENT_ROOT/.venv/bin/robonix-client"
readonly CLIENT_PYTHON="$CLIENT_ROOT/.venv/bin/python"
readonly RUNTIME_ROOT="$DEPLOY_DIR/rbnx-build/client"
readonly SETTINGS_TEMPLATE="$DEPLOY_DIR/config/robonix_client_settings.yaml"
readonly SETTINGS_FILE="$RUNTIME_ROOT/settings.yaml"

if [[ ! -x "$CLIENT_BIN" || ! -x "$CLIENT_PYTHON" ]]; then
  echo "official Robonix Client is not prepared at $CLIENT_ROOT/.venv" >&2
  echo "prepare its Python 3.11 workspace environment before starting this launcher" >&2
  exit 2
fi
if ! "$CLIENT_PYTHON" -c 'import sys; raise SystemExit(sys.version_info < (3, 11))'; then
  echo "official Robonix Client requires Python 3.11 or newer" >&2
  exit 2
fi

mkdir -p "$RUNTIME_ROOT/home" "$RUNTIME_ROOT/cache" "$RUNTIME_ROOT/tmp"
chmod 0700 "$RUNTIME_ROOT" "$RUNTIME_ROOT/home" "$RUNTIME_ROOT/cache" "$RUNTIME_ROOT/tmp"
if [[ ! -e "$SETTINGS_FILE" ]]; then
  install -m 0600 "$SETTINGS_TEMPLATE" "$SETTINGS_FILE"
elif [[ ! -f "$SETTINGS_FILE" || -L "$SETTINGS_FILE" ]]; then
  echo "refusing unsafe client settings path: $SETTINGS_FILE" >&2
  exit 2
fi

readonly AUDIO_MODE="${ROBONIX_CLIENT_ENABLE_AUDIO:-auto}"
case "$AUDIO_MODE" in
  0|false|no|disabled)
    export ROBONIX_CLIENT_REVERSE_AUDIO=0
    ;;
  1|true|yes|enabled)
    if ! "$CLIENT_PYTHON" -c 'import sounddevice' >/dev/null 2>&1; then
      echo "audio was required but PortAudio/sounddevice is unavailable" >&2
      echo "the exact apt and Python install steps require separate approval" >&2
      exit 2
    fi
    export ROBONIX_CLIENT_REVERSE_AUDIO=1
    ;;
  auto)
    if "$CLIENT_PYTHON" -c 'import sounddevice' >/dev/null 2>&1; then
      export ROBONIX_CLIENT_REVERSE_AUDIO=1
    else
      export ROBONIX_CLIENT_REVERSE_AUDIO=0
      echo "[client] local microphone unavailable; starting text UI only" >&2
      echo "[client] local FunASR remains the stack default; audio dependencies need approval" >&2
    fi
    ;;
  *)
    echo "ROBONIX_CLIENT_ENABLE_AUDIO must be auto, enabled, or disabled" >&2
    exit 2
    ;;
esac

# Keep all client state/cache/log writes inside this repository. No credential
# is accepted or generated by this launcher.
export HOME="$RUNTIME_ROOT/home"
export XDG_CONFIG_HOME="$RUNTIME_ROOT/home/.config"
export XDG_CACHE_HOME="$RUNTIME_ROOT/cache"
export TMPDIR="$RUNTIME_ROOT/tmp"
export ROBONIX_CLIENT_SETTINGS="$SETTINGS_FILE"

readonly ROBOT_HOST="${ROBONIX_CLIENT_ROBOT_HOST:-127.0.0.1}"
readonly ATLAS_PORT="${ROBONIX_CLIENT_ATLAS_PORT:-50051}"
readonly CLIENT_PORT="${ROBONIX_CLIENT_PORT:-7860}"

if [[ "$ROBOT_HOST" != "127.0.0.1" ]]; then
  echo "this local operator profile requires ROBONIX_CLIENT_ROBOT_HOST=127.0.0.1" >&2
  exit 2
fi
if [[ ! "$ATLAS_PORT" =~ ^[0-9]+$ || ! "$CLIENT_PORT" =~ ^[0-9]+$ ]]; then
  echo "client and Atlas ports must be decimal integers" >&2
  exit 2
fi

echo "================================================================"
echo " OFFICIAL ROBONIX CLIENT — LOCAL OPERATOR PROFILE"
echo " UI:       http://127.0.0.1:${CLIENT_PORT}/"
echo " Atlas:    ${ROBOT_HOST}:${ATLAS_PORT}"
echo " Audio:    $([[ "$ROBONIX_CLIENT_REVERSE_AUDIO" == 1 ]] && echo enabled || echo text-only)"
echo " This client does not bypass Robonix motion/semantic safety gates."
echo "================================================================"

exec "$CLIENT_BIN" \
  --host 127.0.0.1 \
  --port "$CLIENT_PORT" \
  --robot-host "$ROBOT_HOST" \
  --atlas-port "$ATLAS_PORT" \
  --audio-server-host 127.0.0.1 \
  --audio-server-bind-host 127.0.0.1 \
  --audio-server-ui-host 127.0.0.1
